openapi: 3.0.0
paths:
  /cats:
    post:
      operationId: create
      summary: ''
      description: 创建cat
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCatDto'
      responses:
        '201':
          description: cat创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
        '403':
          description: Forbidden.
      tags: &ref_0
        - cats
    get:
      operationId: findAll
      summary: ''
      description: 查询所有cat
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                title: PaginatedResponseOfCat
                allOf:
                  - $ref: '#/components/schemas/PagedRes'
                  - properties:
                      list:
                        type: array
                        items:
                          $ref: '#/components/schemas/Cat'
      tags: *ref_0
  /cats/{id}:
    get:
      operationId: findOne
      summary: ''
      description: 根据ID查询cat
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
      tags: *ref_0
    patch:
      operationId: update
      summary: ''
      description: 根据ID修改cat
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCatDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
      tags: *ref_0
    delete:
      operationId: remove
      summary: ''
      description: 根据ID删除cat
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
      tags: *ref_0
  /user:
    post:
      operationId: UserController_create
      summary: ''
      description: 创建用户
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: boolean
      tags: &ref_1
        - users
    get:
      operationId: UserController_findAll
      summary: ''
      description: 查找所有用户
      parameters:
        - name: limit
          required: true
          in: query
          schema:
            default: 10
            type: number
        - name: offset
          required: true
          in: query
          schema:
            default: 0
            type: number
        - name: name
          required: false
          in: query
          description: 名字
          schema:
            type: string
        - name: cnName
          required: false
          in: query
          description: 中文姓名
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                title: PaginatedResponseOfUserEntity
                allOf:
                  - $ref: '#/components/schemas/PagedRes'
                  - properties:
                      list:
                        type: array
                        items:
                          $ref: '#/components/schemas/UserEntity'
      tags: *ref_1
  /user/{id}:
    get:
      operationId: UserController_findOne
      summary: ''
      description: 根据ID查询用户信息
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEntity'
      tags: *ref_1
    patch:
      operationId: UserController_update
      summary: ''
      description: 根据ID修改用户信息
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEntity'
      tags: *ref_1
    delete:
      operationId: UserController_remove
      summary: ''
      description: 根据ID删除用户信息
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: boolean
      tags: *ref_1
  /role:
    post:
      operationId: RoleController_create
      summary: ''
      description: 创建角色
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoleDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoleDto'
      tags: &ref_2
        - role
    get:
      operationId: RoleController_findAll
      summary: ''
      description: 查找所有角色
      parameters:
        - name: limit
          required: true
          in: query
          schema:
            default: 10
            type: number
        - name: offset
          required: true
          in: query
          schema:
            default: 0
            type: number
        - name: createBy
          required: false
          in: query
          schema:
            type: string
        - name: createAt
          required: false
          in: query
          schema:
            format: date-time
            type: string
        - name: updateBy
          required: false
          in: query
          schema:
            type: string
        - name: updateAt
          required: false
          in: query
          schema:
            format: date-time
            type: string
        - name: roleId
          required: false
          in: query
          description: 角色ID
          schema:
            type: string
        - name: roleName
          required: false
          in: query
          description: 角色名称
          schema:
            type: string
        - name: remark
          required: false
          in: query
          description: 备注
          schema:
            type: string
        - name: status
          required: false
          in: query
          description: 状态（正常，停用等）
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                title: PaginatedResponseOfRoleEntity
                allOf:
                  - $ref: '#/components/schemas/PagedRes'
                  - properties:
                      list:
                        type: array
                        items:
                          $ref: '#/components/schemas/RoleEntity'
      tags: *ref_2
info:
  title: Cats example
  description: The cats API description
  version: '1.0'
  contact: {}
tags:
  - name: cats
    description: ''
servers: []
components:
  schemas:
    PaginatedDto:
      type: object
      properties:
        limit:
          type: number
          default: 10
        offset:
          type: number
          default: 0
      required:
        - limit
        - offset
    CreateCatDto:
      type: object
      properties:
        name:
          type: string
          description: 名字
        age:
          type: number
          description: 年龄
        breed:
          type: string
          description: 品种
    Cat:
      type: object
      properties:
        name:
          type: string
          description: 名字
        age:
          type: number
          description: 年龄
        breed:
          type: string
          description: 品种
    UpdateCatDto:
      type: object
      properties:
        name:
          type: string
          description: 名字
        age:
          type: number
          description: 年龄
        breed:
          type: string
          description: 品种
    PagedRes:
      type: object
      properties:
        total:
          type: number
          description: 列表总数
        list:
          description: 结果列表
          type: array
          items:
            type: string
    CreateUserDto:
      type: object
      properties:
        name:
          type: string
          description: 名字
        cnName:
          type: string
          description: 中文姓名
        password:
          type: string
          description: 密码
        department:
          type: string
          description: 部门
        roles:
          description: 角色列表
          type: array
          items:
            type: string
        groupId:
          type: string
          description: 分组Id
        phoneNo:
          type: string
          description: 联系方式
        status:
          type: string
          description: 状态（正常，离职，停职等）
      required:
        - name
        - cnName
        - password
    UserEntity:
      type: object
      properties:
        createBy:
          type: string
        createAt:
          format: date-time
          type: string
        updateBy:
          type: string
        updateAt:
          format: date-time
          type: string
        name:
          type: string
          description: 名字
        cnName:
          type: string
          description: 中文姓名
        department:
          type: string
          description: 部门
        roles:
          description: 角色列表
          type: array
          items:
            type: string
        phoneNo:
          type: string
          description: 联系方式
        status:
          type: string
          description: 状态（正常，离职，停职等）
      required:
        - name
        - cnName
    UpdateUserDto:
      type: object
      properties:
        name:
          type: string
          description: 名字
        cnName:
          type: string
          description: 中文姓名
        password:
          type: string
          description: 密码
        department:
          type: string
          description: 部门
        roles:
          description: 角色列表
          type: array
          items:
            type: string
        groupId:
          type: string
          description: 分组Id
        phoneNo:
          type: string
          description: 联系方式
        status:
          type: string
          description: 状态（正常，离职，停职等）
    RoleEntity:
      type: object
      properties:
        roleId:
          type: string
          description: 角色ID
        roleName:
          type: string
          description: 角色名称
        remark:
          type: string
          description: 备注
        status:
          type: string
          description: 状态（正常，停用等）
        createBy:
          type: string
        createAt:
          format: date-time
          type: string
        updateBy:
          type: string
        updateAt:
          format: date-time
          type: string
      required:
        - roleId
        - roleName
        - status
    CreateRoleDto:
      type: object
      properties:
        createBy:
          type: string
        createAt:
          format: date-time
          type: string
        updateBy:
          type: string
        updateAt:
          format: date-time
          type: string
        roleId:
          type: string
          description: 角色ID
        roleName:
          type: string
          description: 角色名称
        remark:
          type: string
          description: 备注
        status:
          type: string
          description: 状态（正常，停用等）
      required:
        - roleId
        - roleName
        - status
